    name: Scheduled Python Script

    on:
      schedule:
        - cron: '1 */4 * * *' # Runs daily at 00:00 
        #- cron: '*/15 * * * *' # Runs every 15 mins

    permissions:
         contents:  write


    jobs:
      run-script:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v1

          #- name: Set up Python
            #uses: actions/setup-python@v5
            #with:
              #python-version: '3.x' # Specify your Python version

          #- name: Install dependencies
            #run: pip install -r requirements.txt # If you have a requirements.txt

          - name: Run Python script
            run: python spocr01.py
